name: 'Setup Skip'
description: 'Installs and condifures the Skip development environment'
branding:
  icon: 'box'
  color: 'blue'

inputs:
  skip-version:
    description: 'The version of the Skip toolchain to install'
    required: true
    default: 'latest'
  run-doctor:
    description: 'Whether to run skip doctor'
    required: false
    default: 'true'
  verify-project:
    description: 'Path to the project to verify'
    required: false
    default: ''
  swift-version:
    description: 'Version of Swift to install'
    required: false
    default: ''
  gradle-version:
    description: 'Version of Gradle to setup'
    required: false
    default: 'current'
  install-swift-android-sdk:
    description: 'Whether to install the native Swift SDK for Android'
    required: false
    default: 'false'
  swift-android-sdk-version:
    description: 'Version of the Swift SDK for Android to install'
    required: false
    default: ''
  verbose:
    description: 'Whether to be verbose when running setup commands'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Install Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@0da5e123f3a792967ae460199673d87e2bfa257d # @main

    - name: Install Gradle
      if: ${{ inputs.gradle-version != '' && inputs.gradle-version != 'none' }}
      uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # @v5
      with:
        gradle-version: ${{ inputs.gradle-version }}
        add-job-summary: 'on-failure'

    - name: Install Swift
      if: ${{ inputs.swift-version != '' }}
      uses: swift-actions/setup-swift@7e293214cba9e9225c93ce3267f17f6efdb656a8 # @next
      with:
        swift-version: ${{ inputs.swift-version }}

    - name: Install Skip
      shell: bash
      run: |
        HOMEBREW_NO_AUTO_UPDATE=1 brew install skiptools/skip/skip
        if [ ${RUNNER_OS} == 'macOS' ]; then
          # enable running the Skip plugin from xcodebuild without user prompt
          defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES
          defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
        fi

    - name: Setup environment
      id: setup
      shell: bash
      run: |
        verbose_arg=""
        if [[ "${{ inputs.verbose }}" ]]; then
          verbose_arg="--verbose"
        fi
        echo "verbose_arg=${verbose_arg}" >> $GITHUB_OUTPUT

    - name: Install Toolchain Dependencies
      shell: bash
      run: |
        if [ ${RUNNER_OS} == 'Linux' ]; then
          # needed to be able to install swiftly toolchains
          sudo apt-get -y install libcurl4-openssl-dev
        fi

    - name: Initialize swiftly
      shell: bash
      run: swiftly init --skip-install --assume-yes

    - name: Install Swift SDK for Android
      if: ${{ inputs.install-swift-android-sdk == 'true' }}
      shell: bash
      run: |
        version_arg=""
        if [[ ! -z "${{ inputs.swift-android-sdk-version }}" ]]; then
          version_arg="--version ${{ inputs.swift-android-sdk-version }}"
        fi

        skip android sdk install ${{ steps.setup.outputs.verbose_arg }} ${version_arg}

        # workaround fail when ANDROID_NDK_ROOT is set
        # see https://github.com/finagolfin/swift-android-sdk/issues/207
        echo "ANDROID_NDK_ROOT=" >> $GITHUB_ENV

    - name: Skip Doctor
      if: ${{ inputs.run-doctor == 'true' }}
      shell: bash
      run: skip doctor ${{ steps.setup.outputs.verbose_arg }}

    - name: Skip Verify Project
      if: ${{ inputs.verify-project != '' }}
      shell: bash
      run: skip verify ${{ steps.setup.outputs.verbose_arg }} --project ${{ inputs.verify-project }}

