name: 'Setup Skip'
description: 'Installs and condifures the Skip development environment'
branding:
  icon: 'box'
  color: 'blue'

inputs:
  skip-version:
    description: 'The version of the Skip toolchain to install'
    required: true
    default: 'latest'
  run-doctor:
    description: 'Whether to run skip doctor'
    required: false
    default: 'true'
  verify-project:
    description: 'Path to the project to verify'
    required: false
    default: ''
  swift-version:
    description: 'Version of Swift to install'
    required: false
    default: ''
  gradle-version:
    description: 'Version of Gradle to setup'
    required: false
    default: 'current'
  install-swift-android-sdk:
    description: 'Whether to install the native Swift SDK for Android'
    required: false
    default: 'false'
  swift-android-sdk-version:
    description: 'Version of the Swift SDK for Android to install'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Install Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@0da5e123f3a792967ae460199673d87e2bfa257d # @main

    - name: Install Gradle
      if: ${{ inputs.gradle-version != '' && inputs.gradle-version != 'none' }}
      uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # @v5
      with:
        gradle-version: ${{ inputs.gradle-version }}
        add-job-summary: 'on-failure'

    - name: Install Swift
      if: ${{ inputs.swift-version != '' }}
      uses: swift-actions/setup-swift@7e293214cba9e9225c93ce3267f17f6efdb656a8 # @next
      with:
        swift-version: ${{ inputs.swift-version }}

    - name: Install Skip
      shell: bash
      run: |
        brew install skiptools/skip/skip
        if [ ${RUNNER_OS} == 'macOS' ]; then
          # enable running the Skip plugin from xcodebuild without user prompt
          defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES
          defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
        fi

    - name: Initialize swiftly
      shell: bash
      run: swiftly init --skip-install --assume-yes

    - name: Install Swift SDK for Android
      if: ${{ inputs.install-swift-android-sdk == 'true' }}
      shell: bash
      run: |
        if [[ ! -z "${{ inputs.swift-android-sdk-version }}" ]]; then
          skip android sdk install --version ${{ inputs.swift-android-sdk-version }}
        else
          skip android sdk install
        fi

    - name: Skip Doctor
      if: ${{ inputs.run-doctor == 'true' }}
      shell: bash
      run: skip doctor

    - name: Skip Verify Project
      if: ${{ inputs.verify-project != '' }}
      shell: bash
      run: skip verify --project ${{ inputs.verify-project }}

